-- AlterTable AuditEvent
ALTER TABLE `AuditEvent` MODIFY COLUMN `eventType` ENUM(
  'ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'LOGIN_ATTEMPT_SUCCESS', 'LOGIN_ATTEMPT_FAILED',
  'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_SUCCESS', 'OTP_SENT', 'OTP_VERIFIED',
  'DEVICE_REGISTERED', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'SERVER_CREATED',
  'SERVER_STARTED', 'SERVER_STOPPED', 'ENDPOINT_ASSIGNED', 'REMOTE_CONNECTION_CREATED',
  'REMOTE_CONNECTION_CONNECTED', 'REMOTE_CONNECTION_DISCONNECTED', 'REMOTE_CONNECTION_FAILED',
  'SERVER_ENDPOINT_ALLOCATED', 'FILE_MANAGER_LOGIN_SUCCESS', 'FILE_MANAGER_LOGIN_FAILED',
  'PUSH_TOKEN_REGISTERED', 'PUSH_TOKEN_UPDATED', 'PUSH_TOKEN_REVOKED', 'NOTIFICATION_CREATED',
  'NOTIFICATION_DELIVERY_FAILED', 'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_ACTIVATED',
  'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_PAST_DUE', 'SUBSCRIPTION_GRACE_PERIOD_STARTED',
  'SUBSCRIPTION_GRACE_PERIOD_RECOVERED', 'SUBSCRIPTION_CANCELLATION_REQUESTED',
  'SUBSCRIPTION_CANCELLATION_REVERSED', 'SUBSCRIPTION_CANCELLED', 'SUBSCRIPTION_EXPIRED',
  'SUBSCRIPTION_REFUNDED', 'SUBSCRIPTION_UPGRADE_REQUESTED', 'SUBSCRIPTION_UPGRADED',
  'SUBSCRIPTION_UPGRADE_RECONCILIATION_MATCHED', 'SUBSCRIPTION_UPGRADE_RECONCILIATION_MISMATCHED',
  'SUBSCRIPTION_DOWNGRADE_REQUESTED', 'SUBSCRIPTION_DOWNGRADE_SCHEDULED',
  'SUBSCRIPTION_DOWNGRADE_CANCEL_REQUESTED', 'SUBSCRIPTION_DOWNGRADE_CANCELLED',
  'SUBSCRIPTION_DOWNGRADE_EFFECTIVE', 'SUBSCRIPTION_DOWNGRADE_MISMATCHED',
  'REFUND_REQUESTED', 'REFUND_PROVIDER_REQUESTED', 'REFUND_PROCESSED', 'REFUND_FAILED',
  'REFUND_REQUIRES_REVIEW', 'REFUND_POLICY_REJECTED', 'REFUND_DUPLICATE_REQUEST', 'REFUND_CANCELLED',
  'BILLING_RECEIPT_CREATED', 'BILLING_RECEIPT_ISSUED', 'BILLING_RECEIPT_GENERATION_FAILED',
  'BILLING_RECEIPT_ACCESSED', 'BILLING_RECEIPT_DOWNLOAD_REQUESTED',
  'TAX_CALCULATED', 'TAX_CALCULATION_FAILED', 'TAX_CONFIGURATION_MISSING',
  'PROCESSING_FEE_RECORDED', 'PROCESSING_FEE_PENDING', 'PROCESSING_FEE_RECONCILIATION_REQUIRED',
  'BILLING_STATE_UPDATED'
) NOT NULL;

-- CreateTable BillingPaymentTax
CREATE TABLE IF NOT EXISTS `BillingPaymentTax` (
  `id` VARCHAR(191) NOT NULL,
  `paymentId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `jurisdiction` VARCHAR(191) NOT NULL,
  `taxType` ENUM('GST', 'SALES_TAX', 'VAT', 'NONE') NOT NULL DEFAULT 'GST',
  `isInclusive` BOOLEAN NOT NULL DEFAULT true,
  `taxRateBasisPoints` INT NOT NULL,
  `taxableAmountMinorUnits` INT NOT NULL,
  `taxAmountMinorUnits` INT NOT NULL,
  `grossAmountMinorUnits` INT NOT NULL,
  `currency` ENUM('INR', 'USD') NOT NULL,
  `taxBreakdown` JSON NULL,
  `taxRegistrationNumber` VARCHAR(191) NULL,
  `customerTaxId` VARCHAR(191) NULL,
  `customerCountry` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `billing_payment_tax_payment_uniq`(`paymentId`),
  INDEX `billing_payment_tax_user_idx`(`userId`),
  INDEX `billing_payment_tax_jurisdiction_idx`(`jurisdiction`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BillingPaymentTax_paymentId_fkey` FOREIGN KEY (`paymentId`) REFERENCES `BillingPayment`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BillingPaymentTax_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable BillingPaymentProcessingFee
CREATE TABLE IF NOT EXISTS `BillingPaymentProcessingFee` (
  `id` VARCHAR(191) NOT NULL,
  `paymentId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
  `feeMinorUnits` INT NOT NULL,
  `taxOnFeeMinorUnits` INT NOT NULL DEFAULT 0,
  `totalFeeMinorUnits` INT NOT NULL,
  `netSettlementMinorUnits` INT NOT NULL,
  `currency` ENUM('INR', 'USD') NOT NULL,
  `isEstimated` BOOLEAN NOT NULL DEFAULT true,
  `isReconciled` BOOLEAN NOT NULL DEFAULT false,
  `reconciledAt` DATETIME(3) NULL,
  `feeBreakdown` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `billing_payment_fee_payment_uniq`(`paymentId`),
  INDEX `billing_payment_fee_user_idx`(`userId`),
  INDEX `billing_payment_fee_reconciled_idx`(`isReconciled`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BillingPaymentProcessingFee_paymentId_fkey` FOREIGN KEY (`paymentId`) REFERENCES `BillingPayment`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BillingPaymentProcessingFee_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
