-- AlterTable admin_audit_logs
ALTER TABLE `admin_audit_logs` 
  MODIFY `action` ENUM('ADMIN_LOGIN_SUCCESS', 'ADMIN_LOGIN_FAILURE', 'ADMIN_LOGOUT', 'ADMIN_SESSION_REVOKED', 'ADMIN_SESSION_EXPIRED', 'ADMIN_AUTH_BLOCKED', 'ADMIN_OTP_SENT', 'ADMIN_OTP_VERIFIED', 'ADMIN_OTP_FAILED', 'ADMIN_ROLE_CREATED', 'ADMIN_ROLE_UPDATED', 'ADMIN_ROLE_ASSIGNED', 'ADMIN_ROLE_REMOVED', 'ADMIN_PERMISSION_ASSIGNED', 'ADMIN_PERMISSION_REMOVED', 'ADMIN_AUTHZ_DENIED', 'ADMIN_SESSION_BOOTSTRAP', 'ADMIN_AUDIT_QUERY', 'ADMIN_AUDIT_EXPORT', 'ADMIN_AUDIT_INTEGRITY_VERIFIED', 'ADMIN_LOCKOUT_TRIGGERED', 'ADMIN_PASSWORD_UPDATED', 'ADMIN_STATUS_UPDATED') NOT NULL,
  ADD COLUMN `previousHash` VARCHAR(64) NULL,
  ADD COLUMN `integrityHash` VARCHAR(64) NULL,
  ADD COLUMN `sequence` INT NULL;

-- CreateIndex on admin_audit_logs(integrityHash)
CREATE INDEX `admin_audit_logs_integrityHash_idx` ON `admin_audit_logs`(`integrityHash`);

-- CreateTable admin_lockouts
CREATE TABLE IF NOT EXISTS `admin_lockouts` (
  `id` VARCHAR(191) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `failedAttempts` INT NOT NULL DEFAULT 0,
  `lockedUntil` DATETIME(3) NULL,
  `lastAttemptAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_lockouts_key_key`(`key`),
  INDEX `admin_lockouts_lockedUntil_idx`(`lockedUntil`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
