-- AlterTable: Add attempts column to EmailOtp
ALTER TABLE `EmailOtp` ADD COLUMN `attempts` INTEGER NOT NULL DEFAULT 0;

-- AlterTable: Update OtpPurpose ENUM with PASSWORD_RESET
ALTER TABLE `EmailOtp` MODIFY COLUMN `purpose` ENUM('REGISTRATION_VERIFICATION', 'LOGIN_2FA', 'PASSWORD_RESET') NOT NULL DEFAULT 'REGISTRATION_VERIFICATION';

-- AlterTable: Update AuditEventType ENUM with PASSWORD_RESET_REQUESTED and PASSWORD_RESET_SUCCESS
ALTER TABLE `AuditEvent` MODIFY COLUMN `eventType` ENUM('ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'LOGIN_ATTEMPT_SUCCESS', 'LOGIN_ATTEMPT_FAILED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_SUCCESS', 'OTP_SENT', 'OTP_VERIFIED', 'DEVICE_REGISTERED', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'SERVER_STARTED', 'SERVER_STOPPED', 'ENDPOINT_ASSIGNED', 'REMOTE_CONNECTION_CREATED', 'REMOTE_CONNECTION_CONNECTED', 'REMOTE_CONNECTION_DISCONNECTED', 'REMOTE_CONNECTION_FAILED', 'SERVER_ENDPOINT_ALLOCATED') NOT NULL;
