-- CreateTable BillingReconciliationRun
CREATE TABLE IF NOT EXISTS `BillingReconciliationRun` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
  `environment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
  `periodStart` DATETIME(3) NOT NULL,
  `periodEnd` DATETIME(3) NOT NULL,
  `status` ENUM('STARTED', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED') NOT NULL DEFAULT 'STARTED',
  `totalRecords` INT NOT NULL DEFAULT 0,
  `paymentRecords` INT NOT NULL DEFAULT 0,
  `refundRecords` INT NOT NULL DEFAULT 0,
  `transferRecords` INT NOT NULL DEFAULT 0,
  `adjustmentRecords` INT NOT NULL DEFAULT 0,
  `matchedCount` INT NOT NULL DEFAULT 0,
  `mismatchCount` INT NOT NULL DEFAULT 0,
  `reviewCount` INT NOT NULL DEFAULT 0,
  `duplicateCount` INT NOT NULL DEFAULT 0,
  `failureCount` INT NOT NULL DEFAULT 0,
  `durationMs` INT NULL,
  `correlationId` VARCHAR(191) NULL,
  `metadata` JSON NULL,
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `billing_recon_run_prov_env_status_idx`(`provider`, `environment`, `status`),
  INDEX `billing_recon_run_period_idx`(`periodStart`, `periodEnd`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable BillingSettlement
CREATE TABLE IF NOT EXISTS `BillingSettlement` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
  `environment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
  `providerSettlementId` VARCHAR(191) NOT NULL,
  `settlementUtr` VARCHAR(191) NULL,
  `settlementCurrency` ENUM('INR', 'USD') NOT NULL DEFAULT 'INR',
  `settlementAmountMinorUnits` INT NOT NULL,
  `providerFeesMinorUnits` INT NOT NULL DEFAULT 0,
  `providerTaxMinorUnits` INT NOT NULL DEFAULT 0,
  `settlementStatus` VARCHAR(191) NOT NULL DEFAULT 'settled',
  `settledAt` DATETIME(3) NULL,
  `reconciliationStatus` ENUM('PENDING', 'MATCHED', 'MISMATCHED', 'REQUIRES_REVIEW', 'RESOLVED', 'IGNORED') NOT NULL DEFAULT 'PENDING',
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `billing_settlement_prov_id_uniq`(`providerSettlementId`),
  INDEX `billing_settlement_status_idx`(`reconciliationStatus`),
  INDEX `billing_settlement_settled_idx`(`settledAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable BillingReconciliationRecord
CREATE TABLE IF NOT EXISTS `BillingReconciliationRecord` (
  `id` VARCHAR(191) NOT NULL,
  `runId` VARCHAR(191) NULL,
  `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
  `environment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
  `providerEntityId` VARCHAR(191) NOT NULL,
  `entityType` ENUM('PAYMENT', 'REFUND', 'TRANSFER', 'ADJUSTMENT', 'SETTLEMENT') NOT NULL,
  `providerPaymentId` VARCHAR(191) NULL,
  `providerRefundId` VARCHAR(191) NULL,
  `providerSettlementId` VARCHAR(191) NULL,
  `settlementUtr` VARCHAR(191) NULL,
  `amountMinorUnits` INT NOT NULL,
  `debitMinorUnits` INT NULL,
  `creditMinorUnits` INT NULL,
  `currency` ENUM('INR', 'USD') NOT NULL DEFAULT 'INR',
  `providerFeeMinorUnits` INT NULL,
  `providerFeeTaxMinorUnits` INT NULL,
  `settled` BOOLEAN NOT NULL DEFAULT false,
  `settledAt` DATETIME(3) NULL,
  `orderId` VARCHAR(191) NULL,
  `internalPaymentId` VARCHAR(191) NULL,
  `internalRefundId` VARCHAR(191) NULL,
  `status` ENUM('PENDING', 'MATCHED', 'MISMATCHED', 'REQUIRES_REVIEW', 'RESOLVED', 'IGNORED') NOT NULL DEFAULT 'PENDING',
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `billing_recon_rec_prov_entity_uniq`(`provider`, `environment`, `providerEntityId`, `entityType`),
  INDEX `billing_recon_rec_run_idx`(`runId`),
  INDEX `billing_recon_rec_prov_pay_idx`(`providerPaymentId`),
  INDEX `billing_recon_rec_prov_setl_idx`(`providerSettlementId`),
  INDEX `billing_recon_rec_status_idx`(`status`),
  CONSTRAINT `BillingReconciliationRecord_runId_fkey` FOREIGN KEY (`runId`) REFERENCES `BillingReconciliationRun`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BillingReconciliationRecord_internalPaymentId_fkey` FOREIGN KEY (`internalPaymentId`) REFERENCES `BillingPayment`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BillingReconciliationRecord_internalRefundId_fkey` FOREIGN KEY (`internalRefundId`) REFERENCES `BillingRefund`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable BillingReconciliationDiscrepancy
CREATE TABLE IF NOT EXISTS `BillingReconciliationDiscrepancy` (
  `id` VARCHAR(191) NOT NULL,
  `runId` VARCHAR(191) NULL,
  `reconciliationRecordId` VARCHAR(191) NULL,
  `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
  `environment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
  `discrepancyType` ENUM('MISSING_INTERNAL_RECORD', 'MISSING_PROVIDER_RECORD', 'AMOUNT_MISMATCH', 'CURRENCY_MISMATCH', 'STATUS_MISMATCH', 'FEE_MISMATCH', 'TAX_MISMATCH', 'SETTLEMENT_MISMATCH', 'DUPLICATE_PROVIDER_TRANSACTION') NOT NULL,
  `severity` ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'MEDIUM',
  `providerEntityId` VARCHAR(191) NULL,
  `internalEntityId` VARCHAR(191) NULL,
  `expectedValue` VARCHAR(191) NULL,
  `actualValue` VARCHAR(191) NULL,
  `details` TEXT NULL,
  `resolved` BOOLEAN NOT NULL DEFAULT false,
  `resolvedAt` DATETIME(3) NULL,
  `resolvedBy` VARCHAR(191) NULL,
  `resolutionNotes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `billing_recon_disc_run_idx`(`runId`),
  INDEX `billing_recon_disc_rec_idx`(`reconciliationRecordId`),
  INDEX `billing_recon_disc_type_idx`(`discrepancyType`),
  INDEX `billing_recon_disc_severity_idx`(`severity`),
  INDEX `billing_recon_disc_resolved_idx`(`resolved`),
  CONSTRAINT `BillingReconciliationDiscrepancy_runId_fkey` FOREIGN KEY (`runId`) REFERENCES `BillingReconciliationRun`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BillingReconciliationDiscrepancy_reconciliationRecordId_fkey` FOREIGN KEY (`reconciliationRecordId`) REFERENCES `BillingReconciliationRecord`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
