-- AlterTable AuditEvent
ALTER TABLE `AuditEvent` MODIFY `eventType` ENUM('ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'LOGIN_ATTEMPT_SUCCESS', 'LOGIN_ATTEMPT_FAILED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_SUCCESS', 'OTP_SENT', 'OTP_VERIFIED', 'DEVICE_REGISTERED', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'SERVER_CREATED', 'SERVER_STARTED', 'SERVER_STOPPED', 'ENDPOINT_ASSIGNED', 'REMOTE_CONNECTION_CREATED', 'REMOTE_CONNECTION_CONNECTED', 'REMOTE_CONNECTION_DISCONNECTED', 'REMOTE_CONNECTION_FAILED', 'SERVER_ENDPOINT_ALLOCATED', 'FILE_MANAGER_LOGIN_SUCCESS', 'FILE_MANAGER_LOGIN_FAILED', 'PUSH_TOKEN_REGISTERED', 'PUSH_TOKEN_UPDATED', 'PUSH_TOKEN_REVOKED', 'NOTIFICATION_CREATED', 'NOTIFICATION_DELIVERY_FAILED', 'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_ACTIVATED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_PAST_DUE', 'SUBSCRIPTION_GRACE_PERIOD_STARTED', 'SUBSCRIPTION_GRACE_PERIOD_RECOVERED', 'SUBSCRIPTION_CANCELLATION_REQUESTED', 'SUBSCRIPTION_EXPIRED', 'SUBSCRIPTION_REFUNDED', 'BILLING_STATE_UPDATED') NOT NULL;

-- CreateTable BillingPayment
CREATE TABLE `BillingPayment` (
    `id` VARCHAR(191) NOT NULL,
    `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
    `environment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
    `providerPaymentId` VARCHAR(191) NULL,
    `providerSubscriptionId` VARCHAR(191) NULL,
    `providerEventId` VARCHAR(191) NULL,
    `userId` VARCHAR(191) NOT NULL,
    `subscriptionId` VARCHAR(191) NOT NULL,
    `amountMinorUnits` INTEGER NOT NULL,
    `currency` ENUM('INR', 'USD') NOT NULL,
    `status` ENUM('SUCCESS', 'FAILED', 'PENDING', 'REFUNDED') NOT NULL DEFAULT 'SUCCESS',
    `chargedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `provider_env_payment_uniq`(`provider`, `environment`, `providerPaymentId`),
    INDEX `billing_payment_user_idx`(`userId`),
    INDEX `billing_payment_sub_idx`(`subscriptionId`),
    INDEX `billing_payment_prov_sub_idx`(`providerSubscriptionId`),
    INDEX `billing_payment_status_idx`(`status`),
    INDEX `billing_payment_charged_idx`(`chargedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BillingPayment` ADD CONSTRAINT `BillingPayment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BillingPayment` ADD CONSTRAINT `BillingPayment_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
