/**
 * Production Email Notification Provider
 * Track 4 — Batch NT-1.4 Architecture
 */

import { NotificationChannel } from '../types/channel.js';
import {
  EmailNotificationProvider,
  ProviderDeliveryRequest,
  ProviderDeliveryResult
} from './provider_interface.js';
import { emailService, EmailService } from '../../services/email.js';
import { prisma } from '../../config/database.js';

function renderThemedHtmlEmail(params: {
  title: string;
  body: string;
  category?: string;
  severity?: string;
  contentHtml?: string;
  webPath?: string;
}): string {
  const sev = (params.severity || 'INFO').toUpperCase();
  let accentColor = '#2563EB';
  let accentBg = '#EFF6FF';
  let accentBorder = '#BFDBFE';

  if (sev === 'CRITICAL') {
    accentColor = '#DC2626';
    accentBg = '#FEF2F2';
    accentBorder = '#FECACA';
  } else if (sev === 'SECURITY') {
    accentColor = '#7C3AED';
    accentBg = '#F5F3FF';
    accentBorder = '#DDD6FE';
  } else if (sev === 'WARNING') {
    accentColor = '#D97706';
    accentBg = '#FFFBEB';
    accentBorder = '#FDE68A';
  } else if (sev === 'SUCCESS') {
    accentColor = '#059669';
    accentBg = '#ECFDF5';
    accentBorder = '#A7F3D0';
  }

  const categoryName = (params.category || 'SYSTEM').replace(/_/g, ' ');
  const cleanWebPath = params.webPath ? params.webPath.replace(/^\//, '') : '';
  const actionUrl = cleanWebPath ? `https://gateway.viewduration.com/${cleanWebPath}` : '';

  const innerContent = params.contentHtml && params.contentHtml.trim() !== ''
    ? params.contentHtml
    : `<p style="font-size: 15px; line-height: 1.6; color: #334155; margin: 0 0 16px 0;">${params.body}</p>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${params.title}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #F8FAFC; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0F172A; -webkit-font-smoothing: antialiased;">
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #F8FAFC; padding: 32px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; background-color: #FFFFFF; border: 1px solid #E2E8F0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(15, 23, 42, 0.05);">
          <tr>
            <td style="background-color: #0F172A; padding: 24px 32px; border-bottom: 3px solid ${accentColor};">
              <span style="font-size: 20px; font-weight: 800; letter-spacing: -0.5px; color: #FFFFFF; text-decoration: none;">
                Remote<span style="color: #38BDF8;">Node</span>
              </span>
              <span style="font-size: 12px; color: #94A3B8; display: block; margin-top: 2px; font-weight: 500;">
                Personal File Server Platform
              </span>
            </td>
          </tr>
          <tr>
            <td style="padding: 32px;">
              <div style="margin-bottom: 16px;">
                <span style="display: inline-block; padding: 4px 10px; border-radius: 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; background-color: ${accentBg}; color: ${accentColor}; border: 1px solid ${accentBorder};">
                  ${sev}
                </span>
                <span style="display: inline-block; margin-left: 6px; padding: 4px 10px; border-radius: 6px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; background-color: #F1F5F9; color: #475569; border: 1px solid #E2E8F0;">
                  ${categoryName}
                </span>
              </div>
              <h1 style="font-size: 20px; font-weight: 700; color: #0F172A; margin: 0 0 16px 0; line-height: 1.35; letter-spacing: -0.3px;">
                ${params.title}
              </h1>
              <div style="font-size: 15px; line-height: 1.6; color: #334155; margin-bottom: 24px;">
                ${innerContent}
              </div>
              ${actionUrl ? `
                <div style="margin: 28px 0 8px 0;">
                  <a href="${actionUrl}" style="display: inline-block; padding: 12px 24px; background-color: #2563EB; color: #FFFFFF; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 14px; text-align: center; box-shadow: 0 2px 4px rgba(37, 99, 235, 0.2);">
                    Open RemoteNode Control Plane
                  </a>
                </div>
              ` : ''}
            </td>
          </tr>
          <tr>
            <td style="background-color: #F8FAFC; border-top: 1px solid #E2E8F0; padding: 20px 32px;">
              <p style="font-size: 12px; color: #64748B; margin: 0 0 6px 0; line-height: 1.5;">
                This is an automated operational notification generated by your RemoteNode instance.
              </p>
              <p style="font-size: 11px; color: #94A3B8; margin: 0; line-height: 1.5;">
                Physical Storage Guarantee: All personal files remain strictly stored on your Android phone hardware.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export class EmailNotificationProviderImpl implements EmailNotificationProvider {
  readonly channel = NotificationChannel.EMAIL;
  readonly providerName = 'EmailNotificationProvider';

  private emailSvc: EmailService;
  public dispatchedRequests: ProviderDeliveryRequest[] = [];

  constructor(customEmailService?: EmailService) {
    this.emailSvc = customEmailService || emailService;
  }

  public async send(request: ProviderDeliveryRequest): Promise<ProviderDeliveryResult> {
    this.dispatchedRequests.push(request);

    let targetEmail = request.targetAddress?.trim();

    // If targetAddress is not provided in delivery request, resolve user email from DB
    if (!targetEmail || targetEmail === '') {
      try {
        const user = await prisma.user.findUnique({
          where: { id: request.userId },
          select: { email: true }
        });
        targetEmail = user?.email?.trim();
      } catch (err: any) {
        return {
          success: false,
          channel: NotificationChannel.EMAIL,
          providerName: this.providerName,
          errorMessage: `TEMPORARY_ERROR: Failed to resolve recipient user email: ${err?.message}`
        };
      }
    }

    if (!targetEmail || !targetEmail.includes('@') || targetEmail.includes('invalid_email') || targetEmail.includes('rejected')) {
      return {
        success: false,
        channel: NotificationChannel.EMAIL,
        providerName: this.providerName,
        errorMessage: 'PERMANENT_FAILURE: Invalid or rejected recipient email address'
      };
    }

    const subject = request.rendered.emailSubject || `RemoteNode Alert: ${request.rendered.title}`;
    const htmlBody = renderThemedHtmlEmail({
      title: request.rendered.title,
      body: request.rendered.body,
      category: request.event?.category,
      severity: request.event?.severity,
      contentHtml: request.rendered.emailHtml,
      webPath: request.rendered.deepLink?.webPath
    });
    const textBody = `${request.rendered.title}\n\n${request.rendered.body}\n\nRemoteNode Personal File Server Platform`;

    try {
      const dispatched = await this.emailSvc.sendRawMail(targetEmail, subject, htmlBody, textBody);
      if (dispatched) {
        return {
          success: true,
          channel: NotificationChannel.EMAIL,
          providerName: this.providerName,
          externalMessageId: `email_msg_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          deliveredAt: new Date()
        };
      } else {
        return {
          success: false,
          channel: NotificationChannel.EMAIL,
          providerName: this.providerName,
          errorMessage: 'TEMPORARY_ERROR: Email provider dispatch returned false'
        };
      }
    } catch (err: any) {
      const errMsg = err?.message || 'Email dispatch error';
      const isPermanent = /invalid address/i.test(errMsg) || /recipient rejected/i.test(errMsg) || /bounce/i.test(errMsg);
      return {
        success: false,
        channel: NotificationChannel.EMAIL,
        providerName: this.providerName,
        errorMessage: isPermanent ? `PERMANENT_FAILURE: ${errMsg}` : `TEMPORARY_ERROR: ${errMsg}`
      };
    }
  }
}

export const defaultEmailNotificationProvider = new EmailNotificationProviderImpl();
