-- AlterTable AuditEvent
ALTER TABLE `AuditEvent` MODIFY `eventType` ENUM('ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'LOGIN_ATTEMPT_SUCCESS', 'LOGIN_ATTEMPT_FAILED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_SUCCESS', 'OTP_SENT', 'OTP_VERIFIED', 'DEVICE_REGISTERED', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'SERVER_CREATED', 'SERVER_STARTED', 'SERVER_STOPPED', 'ENDPOINT_ASSIGNED', 'REMOTE_CONNECTION_CREATED', 'REMOTE_CONNECTION_CONNECTED', 'REMOTE_CONNECTION_DISCONNECTED', 'REMOTE_CONNECTION_FAILED', 'SERVER_ENDPOINT_ALLOCATED', 'FILE_MANAGER_LOGIN_SUCCESS', 'FILE_MANAGER_LOGIN_FAILED', 'PUSH_TOKEN_REGISTERED', 'PUSH_TOKEN_UPDATED', 'PUSH_TOKEN_REVOKED', 'NOTIFICATION_CREATED', 'NOTIFICATION_DELIVERY_FAILED', 'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_ACTIVATED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_PAST_DUE', 'SUBSCRIPTION_GRACE_PERIOD_STARTED', 'SUBSCRIPTION_GRACE_PERIOD_RECOVERED', 'SUBSCRIPTION_CANCELLATION_REQUESTED', 'SUBSCRIPTION_CANCELLATION_REVERSED', 'SUBSCRIPTION_CANCELLED', 'SUBSCRIPTION_EXPIRED', 'SUBSCRIPTION_REFUNDED', 'SUBSCRIPTION_UPGRADE_REQUESTED', 'SUBSCRIPTION_UPGRADED', 'BILLING_STATE_UPDATED') NOT NULL;

-- CreateTable SubscriptionPlanChange
CREATE TABLE `SubscriptionPlanChange` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `subscriptionId` VARCHAR(191) NOT NULL,
    `fromPlanId` VARCHAR(191) NOT NULL,
    `fromPlanPriceId` VARCHAR(191) NOT NULL,
    `toPlanId` VARCHAR(191) NOT NULL,
    `toPlanPriceId` VARCHAR(191) NOT NULL,
    `fromAmountMinorUnits` INTEGER NOT NULL,
    `toAmountMinorUnits` INTEGER NOT NULL,
    `currency` ENUM('INR', 'USD') NOT NULL,
    `creditMinorUnits` INTEGER NOT NULL,
    `netAmountMinorUnits` INTEGER NOT NULL,
    `provider` ENUM('RAZORPAY') NOT NULL DEFAULT 'RAZORPAY',
    `providerEnvironment` ENUM('TEST', 'LIVE') NOT NULL DEFAULT 'TEST',
    `providerSubscriptionId` VARCHAR(191) NULL,
    `status` ENUM('CREATED', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'CREATED',
    `failureReason` TEXT NULL,
    `requestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `SubscriptionPlanChange_userId_idx`(`userId`),
    INDEX `SubscriptionPlanChange_subscriptionId_idx`(`subscriptionId`),
    INDEX `SubscriptionPlanChange_status_idx`(`status`),
    INDEX `SubscriptionPlanChange_requestedAt_idx`(`requestedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_userId_fkey` FOREIGN KEY (`userId` ) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_fromPlanId_fkey` FOREIGN KEY (`fromPlanId`) REFERENCES `Plan`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_toPlanId_fkey` FOREIGN KEY (`toPlanId`) REFERENCES `Plan`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_fromPlanPriceId_fkey` FOREIGN KEY (`fromPlanPriceId`) REFERENCES `PlanPrice`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionPlanChange` ADD CONSTRAINT `SubscriptionPlanChange_toPlanPriceId_fkey` FOREIGN KEY (`toPlanPriceId`) REFERENCES `PlanPrice`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
